In [9]:
import re
import gspread
import pandas as pd
from google.oauth2.service_account import Credentials

In [7]:
SERVICE_ACCOUNT_FILE = 'key/Credentials.json'
SCOPES = ['https://www.googleapis.com/auth/spreadsheets',
          'https://www.googleapis.com/auth/drive']
creds = Credentials.from_service_account_file(
    SERVICE_ACCOUNT_FILE, scopes=SCOPES
)
client = gspread.authorize(creds)

sheet = client.open('[4] AI QC Inbound CRM Review 语音智能质检打标复审').worksheet('Sheet4')
data = sheet.get_all_records()

df = pd.DataFrame(data[1:], columns=data[0])

In [8]:
df

                                                      a
0                                   2026-03-16 15:24:55
1                                                    6″
2     yang paling besar limitnya itu yang disuruh me...
3                                                   Tag
4                                       2021512205(uid)
...                                                 ...
2179                                                Tag
2180                                    2021512205(uid)
2181                                2026-03-16 15:41:46
2182                                                 0″
2183                                       selamat sore

[2184 rows x 1 columns]

In [14]:
col = df['a']

date_pattern = r'\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}'

dates = []
uid_found = False

for val in col:
    if isinstance(val, str) and 'uid' in val:
        uid_found = True
        continue

    if isinstance(val, str) and re.match(date_pattern, val):
        if uid_found:
            dates.append(val)
            uid_found = False

result = pd.DataFrame({'Extracted Dates': dates})

result

         Extracted Dates
0    2026-03-16 15:25:01
1    2026-03-16 15:25:03
2    2026-03-16 15:25:09
3    2026-03-16 15:25:11
4    2026-03-16 15:25:18
..                   ...
228  2026-03-16 15:41:21
229  2026-03-16 15:41:22
230  2026-03-16 15:41:44
231  2026-03-16 15:41:46
232  2026-03-16 15:41:46

[233 rows x 1 columns]