In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('temp/ai语音数据 - Sheet1.csv')
df

,序号,QC,原始语音,Kalimat (fixed),Intonasi,Device
0,https://bit.ly/ai_qc_text_to_speech,NaN,NaN,NaN,NaN,NaN
1,1,Azer,gak ada pemotongan bunga nya,NaN,NaN,NaN
2,2,Azer,saya bayar nya tgl q8,NaN,NaN,NaN
3,3,Azer,kenapa saya tidak bisa mengajukan pinjaman,NaN,NaN,NaN
4,4,Azer,kenapa saya tidak bisa melakukan melakukan pin...,NaN,NaN,NaN
...,...,...,...,...,...,...
469,469,Reza,isi puasa saya.,NaN,NaN,NaN
470,470,Reza,"kenapa paylater saya tidak bisa digunakan,pada...",NaN,NaN,NaN
471,471,Reza,kenapa tidak ada layanan untuk bca?,NaN,NaN,NaN
472,472,Reza,Saya ingin membeli ponsel Apple warna biru,NaN,NaN,NaN
473,473,Reza,i want to buy a phone,NaN,NaN,NaN

In [13]:
df_clean = df[1:]
df_clean

,序号,QC,原始语音,Kalimat (fixed),Intonasi,Device
1,1,Azer,gak ada pemotongan bunga nya,NaN,NaN,NaN
2,2,Azer,saya bayar nya tgl q8,NaN,NaN,NaN
3,3,Azer,kenapa saya tidak bisa mengajukan pinjaman,NaN,NaN,NaN
4,4,Azer,kenapa saya tidak bisa melakukan melakukan pin...,NaN,NaN,NaN
5,5,Azer,kenapa saya tidak bisa melakukan pinjaman dana...,NaN,NaN,NaN
...,...,...,...,...,...,...
469,469,Reza,isi puasa saya.,NaN,NaN,NaN
470,470,Reza,"kenapa paylater saya tidak bisa digunakan,pada...",NaN,NaN,NaN
471,471,Reza,kenapa tidak ada layanan untuk bca?,NaN,NaN,NaN
472,472,Reza,Saya ingin membeli ponsel Apple warna biru,NaN,NaN,NaN
473,473,Reza,i want to buy a phone,NaN,NaN,NaN